name: ğŸš€ Train Model with DVC inside Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ” Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u vishnushankar1 --password-stdin

      - name: ğŸ³ Pull Docker image from GHCR
        run: docker pull ghcr.io/vishnushankar1/churn-fastapi:latest

      - name: ğŸ“¥ Pull data from DagsHub
        run: |
          docker run \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e DAGSHUB_USER=${{ secrets.DAGSHUB_USER }} \
            -e DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
            ghcr.io/vishnushankar1/churn-fastapi:latest \
            /bin/bash -c "git config --global credential.helper store && echo https://${DAGSHUB_USER}:${DAGSHUB_TOKEN}@dagshub.com > ~/.git-credentials && dvc pull"

      - name: ğŸƒ Run DVC pipeline
        run: |
          docker run \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/vishnushankar1/churn-fastapi:latest \
            dvc repro
